version: "2"

services:
  data:
    build: db
    command: "true"
    volumes:
      - /var/lib/postgresql
  db:
    build: db
    restart: always
    environment:
      POSTGRES_IK_PASSWORD: 1k1n1s1sRulz
      POSTGRES_IK_USER: inkinisis
      POSTGRES_IK_DB: inkinisis_db
    volumes_from:
      - data
  app:
    build: app
    links:
      - db
    ports:
      - "13000:3000"
    environment:
      - PGHOST=db
      - PGDATABASE=inkinisis_db
      - PGUSER=inkinisis
    depends_on:
      - db
    command: bash -c "npm start"
    restart: always
    volumes:
      # Mount the app dir in the container as /src so our changes to the app code
      # are also changed in the container
      - /private/inkinisis:/src
  web:
    restart: always
    build: web
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - app
    links:
      - app
    environment:
      - NGINX_DOMAIN=inkinisis.dev
      - NGINX_HTTP_PORT=80
      - NGINX_HTTPS_PORT=443
    command: /bin/bash -c "envsubst '$$NGINX_DOMAIN $$NGINX_HTTP_PORT $$NGINX_HTTPS_PORT' < /etc/nginx/conf.d/inkinisis.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"