version: "2"

services:
  data:
    build: db
    command: "true"
    volumes:
      - /var/lib/postgresql
  db:
    build: db
    restart: always
    environment:
      - POSTGRES_IK_PASSWORD=${POSTGRES_IK_PASSWORD}
      - POSTGRES_IK_USER=${POSTGRES_IK_USER}
      - POSTGRES_IK_DB=${POSTGRES_IK_DB}
    ports:
        - "15432:5432"
    volumes_from:
      - data
  app:
    image: peopleperhour/talentdesk_app
    links:
      - db
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - APP=${APP}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - db
    restart: always
    volumes:
      # Mount the app dir in the container as /src so our changes to the app code
      # are also changed in the container
      - /private/inkinisis:/src
    command: bash -c "pm2-docker ecosystem.config.js --only $$APP"
  web:
    image: peopleperhour/talentdesk_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - app
    links:
      - app
    environment:
      - APP_CONTAINER_NAME=${APP_CONTAINER_NAME}
      - NGINX_DOMAIN=${NGINX_DOMAIN}
      - NGINX_HTTP_PORT=${NGINX_HTTP_PORT}
      - NGINX_HTTPS_PORT=${NGINX_HTTPS_PORT}
      - NODE_PORT=${NODE_PORT}
      - WEBPACK_DEV_SERVER_PORT=${WEBPACK_DEV_SERVER_PORT}
    command: /bin/bash -c "envsubst '$$APP_CONTAINER_NAME $$NGINX_DOMAIN $$NGINX_HTTP_PORT $$NGINX_HTTPS_PORT $$NODE_PORT $$WEBPACK_DEV_SERVER_PORT' < /etc/nginx/conf.d/default-conf.template > /etc/nginx/conf.d/default.conf && envsubst '$$NGINX_DOMAIN' < /etc/nginx/nginx-conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"