#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $POSTGRES_IK_USER;
    CREATE DATABASE $POSTGRES_IK_DB;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_IK_DB to $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_IK_DB to $POSTGRES_IK_USER;
EOSQL
